import { ethers } from "ethers";
import { getContractAddresses } from "./web3";

// Import ABIs (will be generated by deployment script)
import AgentNFTAbi from "@/constants/AgentNFT.json";
import AgentMarketplaceAbi from "@/constants/AgentMarketplace.json";
import AgentCreditsAbi from "@/constants/AgentCredits.json";
import RevenueShareAbi from "@/constants/RevenueShare.json";

export function getAgentNFTContract(
  signerOrProvider: ethers.Signer | ethers.Provider,
  chainId: number
) {
  const addresses = getContractAddresses(chainId);
  return new ethers.Contract(addresses.AgentNFT, AgentNFTAbi, signerOrProvider);
}

export function getMarketplaceContract(
  signerOrProvider: ethers.Signer | ethers.Provider,
  chainId: number
) {
  const addresses = getContractAddresses(chainId);
  return new ethers.Contract(
    addresses.AgentMarketplace,
    AgentMarketplaceAbi,
    signerOrProvider
  );
}

export function getCreditsContract(
  signerOrProvider: ethers.Signer | ethers.Provider,
  chainId: number
) {
  const addresses = getContractAddresses(chainId);
  return new ethers.Contract(
    addresses.AgentCredits,
    AgentCreditsAbi,
    signerOrProvider
  );
}

export function getRevenueShareContract(
  signerOrProvider: ethers.Signer | ethers.Provider,
  chainId: number
) {
  const addresses = getContractAddresses(chainId);
  return new ethers.Contract(
    addresses.RevenueShare,
    RevenueShareAbi,
    signerOrProvider
  );
}

// Mint Agent NFT
export async function mintAgentNFT(
  signer: ethers.Signer,
  chainId: number,
  name: string,
  tokenURI: string,
  personalityHash: string,
  mintingFee: bigint
) {
  const contract = getAgentNFTContract(signer, chainId);
  const tx = await contract.mintAgent(name, tokenURI, personalityHash, {
    value: mintingFee,
  });
  const receipt = await tx.wait();

  // Extract token ID from event
  const event = receipt.logs.find((log: any) => {
    try {
      const parsed = contract.interface.parseLog(log);
      return parsed?.name === "AgentMinted";
    } catch {
      return false;
    }
  });

  if (event) {
    const parsed = contract.interface.parseLog(event);
    return Number(parsed?.args[0]); // tokenId
  }

  return null;
}

// Get minting fee
export async function getMintingFee(
  provider: ethers.Provider,
  chainId: number
): Promise<bigint> {
  const contract = getAgentNFTContract(provider, chainId);
  return await contract.mintingFee();
}

// Get user's agents
export async function getUserAgents(
  provider: ethers.Provider,
  chainId: number,
  address: string
): Promise<number[]> {
  const contract = getAgentNFTContract(provider, chainId);
  const agents = await contract.getAgentsByOwner(address);
  return agents.map((id: bigint) => Number(id));
}

// Get agent metadata
export async function getAgentMetadata(
  provider: ethers.Provider,
  chainId: number,
  tokenId: number
) {
  const contract = getAgentNFTContract(provider, chainId);
  return await contract.getAgentMetadata(tokenId);
}

// ============ Credits Contract Functions ============

// Get user's credit balance
export async function getUserCredits(
  provider: ethers.Provider,
  chainId: number,
  address: string
): Promise<bigint> {
  const contract = getCreditsContract(provider, chainId);
  return await contract.getUserCredits(address);
}

// Get credit price
export async function getCreditPrice(
  provider: ethers.Provider,
  chainId: number
): Promise<bigint> {
  const contract = getCreditsContract(provider, chainId);
  return await contract.creditPrice();
}

// Claim free tier credits
export async function claimFreeTierCredits(
  signer: ethers.Signer,
  chainId: number
) {
  const contract = getCreditsContract(signer, chainId);
  const tx = await contract.claimFreeTier();
  return await tx.wait();
}

// Purchase credits
export async function purchaseCredits(
  signer: ethers.Signer,
  chainId: number,
  amount: number,
  totalCost: bigint
) {
  const contract = getCreditsContract(signer, chainId);
  const tx = await contract.purchaseCredits(amount, { value: totalCost });
  return await tx.wait();
}

// Purchase credit plan
export async function purchaseCreditPlan(
  signer: ethers.Signer,
  chainId: number,
  planId: number,
  planPrice: bigint
) {
  const contract = getCreditsContract(signer, chainId);
  const tx = await contract.purchasePlan(planId, { value: planPrice });
  return await tx.wait();
}

// Get active credit plans
export async function getActiveCreditPlans(
  provider: ethers.Provider,
  chainId: number
) {
  const contract = getCreditsContract(provider, chainId);
  return await contract.getActivePlans();
}

// Check if user claimed free tier
export async function hasClaimedFreeTier(
  provider: ethers.Provider,
  chainId: number,
  address: string
): Promise<boolean> {
  const contract = getCreditsContract(provider, chainId);
  return await contract.hasClaimedFreeTier(address);
}
